name: Trigger PIAS Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - infra/**
      - '.github/workflows/infra.yml'

jobs:
  PFIAS:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Invoke PIAS workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: infra
          repo: IEA-Paris/PIAS
          token: ${{ secrets.SERVICE_USER_PAT }}
          ref: refs/heads/main
          inputs: '{ "name": "PFIAS", "domain": "france", "acm_certificate_arn": "arn:aws:acm:us-east-1:720928668014:certificate/af936a71-516a-40fc-8187-121807242a41"}'
